recipes:
- id: building-1
  requirements:
  - id: material-1
    amount: 4
  - id: material-2
    amount: 15
  - id: material-3
    amount: 100
- id: building-2
  requirements:
  - id: material-1
    amount: 16
materials:
- id: material-1
  name: Composite Material
- id: material-2
  name: Base Material 1
- id: material-3
  name: Base Material 2
buildings:
- id: building-1
  name: Electromagnetic Generator
- id: building-2
  name: Supply Depot
